# Generated by Django 6.0.5 on 2026-05-26 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('capa_url', models.URLField(blank=True)),
                ('sinopse', models.TextField(blank=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('ol_key', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lido', 'Lido'), ('lendo', 'Lendo'), ('quero_ler', 'Quero Ler')], default='quero_ler', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
