# Generated by Django 6.0.5 on 2026-05-26 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_sugerido', models.CharField(max_length=300)),
                ('autor_sugerido', models.CharField(blank=True, max_length=200)),
                ('justificativa', models.TextField()),
                ('humor_informado', models.CharField(blank=True, max_length=200)),
                ('genero_informado', models.CharField(blank=True, max_length=200)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='Retrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retratos', to='livros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retratos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
