# Generated by Django 6.0.5 on 2026-07-20 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas_por_hora', models.FloatField()),
                ('horas_por_dia', models.FloatField()),
                ('quantidade_livros', models.IntegerField()),
                ('texto_livre', models.TextField(blank=True)),
                ('conteudo_ia', models.TextField(blank=True)),
                ('duracao_estimada_dias', models.IntegerField(blank=True, null=True)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
                ('subgenero', models.CharField(blank=True, max_length=100)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='retratos.planoleitura')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoLivroSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('paginas_estimadas', models.IntegerField(blank=True, null=True)),
                ('semana_sugerida', models.IntegerField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_sugeridos', to='retratos.planoleitura')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.DeleteModel(
            name='Recomendacao',
        ),
    ]
