# Generated by Django 6.0.5 on 2026-05-26 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anotacoes', '0001_initial'),
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='livros.livro'),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
